title: My site
author: miroslav resanovic
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ovo je opis moga sajta koji ce se sa necim baviti

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
